import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'

const zh = {
  app: { name: 'FocusFlow', preview: '浏览器预览数据' },
  nav: { dashboard: '概览', today: '今天', tasks: '任务', focus: '专注', statistics: '统计', memo: '备忘录', history: '历史', settings: '设置' },
  common: { add: '新建', save: '保存', cancel: '取消', delete: '删除', edit: '编辑', search: '搜索', reset: '恢复默认', minutes: '分钟', all: '全部', none: '无', close: '关闭', start: '开始', pause: '暂停', resume: '继续', finish: '结束', abandon: '放弃', export: '导出', import: '导入' },
  dashboard: { greeting: '今天，专注真正重要的事', todayTasks: '今日任务', completed: '已完成任务', focusToday: '今日专注', streak: '连续专注', weekFocus: '本周专注', days: '天', current: '当前任务', recentMemos: '最近备忘录', trend: '本周专注趋势', quickStart: '快速开始专注', items: '项' },
  tasks: { title: '任务', subtitle: '组织、排序并推进你的工作', new: '新建任务', edit: '编辑任务', empty: '还没有符合条件的任务', titleLabel: '任务名称', description: '描述', category: '分类', project: '项目', estimate: '预计专注', estimateHint: '可留空，适用于长期计划或非专注型任务', estimateOptional: '可不填写', due: '截止时间', tags: '标签', recurrence: '重复', importance: '重要性', urgency: '紧急性', view: '视图', matrix: '象限', list: '列表', compact: '紧凑', card: '卡片', kanban: '项目看板', four: '四象限', nine: '九象限', todo: '待办', doing: '进行中', done: '已完成', archived: '已归档', active: '进行中的任务', statusFilter: '状态筛选', addCategory: '添加分类', addProject: '添加项目', noCategory: '未分类任务', noProject: '无项目', unassignedProject: '未分类', emptyProject: '这个项目中暂无任务', pinned: '已固定', pin: '固定任务', complete: '完成任务', restore: '恢复任务', searchPlaceholder: '搜索任务、描述或标签…' },
  recurrence: { none: '不重复', daily: '每天', weekdays: '工作日', weekly: '每周', monthly: '每月' },
  matrix: { importantUrgent: '重要且紧急', importantNotUrgent: '重要但不紧急', notImportantUrgent: '不重要但紧急', notImportantNotUrgent: '不重要且不紧急', low: '低', medium: '中', high: '高' },
  focus: { title: '专注', subtitle: '把注意力留给当下的一件事', pomodoro: '番茄钟', stopwatch: '正向计时', selectTask: '绑定任务（可选）', focusPhase: '专注', shortBreak: '短休息', longBreak: '长休息', overtime: '延长', note: '本次专注备注', noTimer: '选择一个任务，开始专注', thisDuration: '本次专注时长', decreaseDuration: '减少 5 分钟', increaseDuration: '增加 5 分钟', defaultDurationHint: '设置页保存新专注的默认时长', discarded: '未达到最短记录门槛，本次专注未保存', saved: '专注记录已保存', autoFinished: '已达到设定时长，专注记录已自动保存' },
  stats: { title: '统计', subtitle: '从原始专注记录中看见投入', total: '总专注时间', average: '平均专注', sessions: '专注次数', completed: '完成任务', focusDays: '专注天数', longest: '最长单次', daily: '每日专注', projects: '项目分布', noProjectData: '暂无项目专注数据' },
  memo: { title: '备忘录', subtitle: '快速保存想法与学习笔记', new: '新建备忘录', untitled: '无标题', content: '使用 Markdown 记录…', empty: '还没有备忘录', category: '备忘录分类', categoryFilter: '分类筛选', allCategories: '全部分类', noCategory: '未分类', addCategory: '新建分类', categoryName: '分类名称', pin: '固定备忘录', formatToolbar: 'Markdown 格式工具栏', bold: '加粗', italic: '斜体', heading: '二级标题', unorderedList: '无序列表', orderedList: '有序列表', taskList: '待办列表', quote: '引用', inlineCode: '行内代码', listItem: '列表项目', boldText: '加粗文字', italicText: '斜体文字', codeText: '代码' },
  history: { title: '专注历史', subtitle: '每一段有效投入都可追溯', empty: '还没有专注记录', task: '任务', time: '时间', duration: '时长', mode: '模式', note: '备注', freeFocus: '自由专注' },
  settings: { title: '设置', subtitle: '让 FocusFlow 适应你的工作方式', appearance: '外观与语言', timer: '专注与记录', matrix: '优先级矩阵', data: '数据与备份', desktop: '桌面能力', theme: '主题', language: '界面语言', light: '浅色', dark: '深色', system: '跟随系统', accent: '强调色', dashboardQuote: '首页语录', dashboardQuoteHint: '留空时使用当前界面的默认语录，最多 80 个字符。', pomodoro: '默认番茄专注时长', streakGoal: '专注日门槛', minimumPercent: '最短记录比例', exemption: '长任务豁免阈值', preventSleep: '专注期间阻止自动休眠', autoOvertime: '番茄到点后自动延长', overtime: '最长延长时间', autoBackup: '每日自动备份', shortcuts: '全局快捷键', noShortcut: '未设置时不启用', closeToTray: '关闭窗口时最小化到系统托盘', closeToTrayHint: '开启后，右上角关闭按钮会隐藏窗口；可从右下角托盘重新打开或真正退出。', taskPanel: '任务浮动面板', timerPanel: '计时浮动面板', enabled: '启用面板', opacity: '背景不透明度', snap: '靠边吸附', alwaysTop: '始终置顶', positionLock: '锁定位置', fourThreshold: '四象限分界值', nineLow: '九宫格低值', nineHigh: '九宫格高值', backupDatabase: '备份数据库', backupSaved: '数据库已备份', previewBackup: '浏览器预览已导出 JSON 备份', imported: '数据导入成功', importNote: '导入前会校验 FocusFlow 备份格式；桌面版替换数据前会创建安全备份。' },
}

const en = {
  app: { name: 'FocusFlow', preview: 'Browser preview data' },
  nav: { dashboard: 'Dashboard', today: 'Today', tasks: 'Tasks', focus: 'Focus', statistics: 'Statistics', memo: 'Memo', history: 'History', settings: 'Settings' },
  common: { add: 'Add', save: 'Save', cancel: 'Cancel', delete: 'Delete', edit: 'Edit', search: 'Search', reset: 'Reset', minutes: 'minutes', all: 'All', none: 'None', close: 'Close', start: 'Start', pause: 'Pause', resume: 'Resume', finish: 'Finish', abandon: 'Abandon', export: 'Export', import: 'Import' },
  dashboard: { greeting: 'Focus on what matters today', todayTasks: "Today's tasks", completed: 'Completed', focusToday: 'Focus today', streak: 'Current streak', weekFocus: 'This week', days: 'days', current: 'Current task', recentMemos: 'Recent memos', trend: 'Weekly focus trend', quickStart: 'Quick focus', items: 'items' },
  tasks: { title: 'Tasks', subtitle: 'Organize, prioritize, and move work forward', new: 'New task', edit: 'Edit task', empty: 'No matching tasks', titleLabel: 'Task title', description: 'Description', category: 'Category', project: 'Project', estimate: 'Focus estimate', estimateHint: 'Optional for long-term plans and non-focus tasks', estimateOptional: 'Optional', due: 'Due', tags: 'Tags', recurrence: 'Repeat', importance: 'Importance', urgency: 'Urgency', view: 'View', matrix: 'Matrix', list: 'List', compact: 'Compact', card: 'Cards', kanban: 'Project board', four: 'Four quadrants', nine: 'Nine grid', todo: 'To do', doing: 'Doing', done: 'Done', archived: 'Archived', active: 'Active tasks', statusFilter: 'Status filter', addCategory: 'Add category', addProject: 'Add project', noCategory: 'Uncategorized tasks', noProject: 'No project', unassignedProject: 'Unassigned', emptyProject: 'No tasks in this project', pinned: 'Pinned', pin: 'Pin task', complete: 'Complete task', restore: 'Restore task', searchPlaceholder: 'Search tasks, descriptions, or tags…' },
  recurrence: { none: 'None', daily: 'Daily', weekdays: 'Weekdays', weekly: 'Weekly', monthly: 'Monthly' },
  matrix: { importantUrgent: 'Important & urgent', importantNotUrgent: 'Important, not urgent', notImportantUrgent: 'Not important, urgent', notImportantNotUrgent: 'Not important or urgent', low: 'Low', medium: 'Medium', high: 'High' },
  focus: { title: 'Focus', subtitle: 'Give your attention to one thing', pomodoro: 'Pomodoro', stopwatch: 'Stopwatch', selectTask: 'Link a task (optional)', focusPhase: 'Focus', shortBreak: 'Short break', longBreak: 'Long break', overtime: 'Overtime', note: 'Session note', noTimer: 'Choose a task and begin', thisDuration: 'This session duration', decreaseDuration: 'Decrease by 5 minutes', increaseDuration: 'Increase by 5 minutes', defaultDurationHint: 'Settings stores the default for new sessions', discarded: 'This session did not meet the recording threshold', saved: 'Focus session saved', autoFinished: 'Time limit reached; focus session saved automatically' },
  stats: { title: 'Statistics', subtitle: 'See your effort from raw focus sessions', total: 'Total focus', average: 'Average session', sessions: 'Sessions', completed: 'Completed tasks', focusDays: 'Focus days', longest: 'Longest session', daily: 'Daily focus', projects: 'Project distribution', noProjectData: 'No project focus data' },
  memo: { title: 'Memo', subtitle: 'Capture ideas and learning notes', new: 'New memo', untitled: 'Untitled', content: 'Write in Markdown…', empty: 'No memos yet', category: 'Memo category', categoryFilter: 'Category filter', allCategories: 'All categories', noCategory: 'Uncategorized', addCategory: 'New category', categoryName: 'Category name', pin: 'Pin memo', formatToolbar: 'Markdown formatting toolbar', bold: 'Bold', italic: 'Italic', heading: 'Heading 2', unorderedList: 'Bullet list', orderedList: 'Numbered list', taskList: 'Task list', quote: 'Quote', inlineCode: 'Inline code', listItem: 'List item', boldText: 'bold text', italicText: 'italic text', codeText: 'code' },
  history: { title: 'Focus history', subtitle: 'Every valid focus session stays traceable', empty: 'No focus sessions yet', task: 'Task', time: 'Time', duration: 'Duration', mode: 'Mode', note: 'Note', freeFocus: 'Free focus' },
  settings: { title: 'Settings', subtitle: 'Make FocusFlow fit your workflow', appearance: 'Appearance & language', timer: 'Focus & recording', matrix: 'Priority matrix', data: 'Data & backup', desktop: 'Desktop features', theme: 'Theme', language: 'Language', light: 'Light', dark: 'Dark', system: 'System', accent: 'Accent color', dashboardQuote: 'Dashboard quote', dashboardQuoteHint: 'Leave blank to use the default for the current language. Maximum 80 characters.', pomodoro: 'Default Pomodoro duration', streakGoal: 'Focus day threshold', minimumPercent: 'Minimum record ratio', exemption: 'Long-task exemption', preventSleep: 'Prevent sleep while focusing', autoOvertime: 'Continue after Pomodoro ends', overtime: 'Maximum overtime', autoBackup: 'Daily automatic backup', shortcuts: 'Global shortcuts', noShortcut: 'Disabled until configured', closeToTray: 'Minimize to system tray on close', closeToTrayHint: 'When enabled, closing hides the window. Use the tray icon to reopen FocusFlow or exit.', taskPanel: 'Task floating panel', timerPanel: 'Timer floating panel', enabled: 'Enable panel', opacity: 'Background opacity', snap: 'Edge snapping', alwaysTop: 'Always on top', positionLock: 'Lock position', fourThreshold: 'Four-quadrant threshold', nineLow: 'Nine-grid low', nineHigh: 'Nine-grid high', backupDatabase: 'Back up database', backupSaved: 'Database backed up', previewBackup: 'Browser preview exported a JSON backup', imported: 'Data imported successfully', importNote: 'FocusFlow validates backup data before import. Desktop builds create a safety backup before replacement.' },
}

void i18n.use(initReactI18next).init({ resources: { 'zh-CN': { translation: zh }, 'en-US': { translation: en } }, lng: 'zh-CN', fallbackLng: 'en-US', interpolation: { escapeValue: false } })

export default i18n
