import { useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { Button } from '../../components/ui/Button'
import { Field, Input, Select, Textarea } from '../../components/ui/Field'
import { useAppStore } from '../../stores/app-store'
import type { Priority, Task } from '../../types/domain'
import { fromLocalInput, toLocalInput } from '../../utils/time'

export function TaskForm({ onDone, initialDate, task }: { onDone(): void; initialDate?: string; task?: Task }) {
  const { t } = useTranslation(); const addTask = useAppStore((s) => s.addTask); const updateTask = useAppStore((s) => s.updateTask); const allCategories = useAppStore((s) => s.data.categories); const allProjects = useAppStore((s) => s.data.projects); const categories = useMemo(() => allCategories.filter((x) => !x.deleted_at), [allCategories]); const projects = useMemo(() => allProjects.filter((x) => !x.deleted_at && !x.is_archived), [allProjects]); const addCategory = useAppStore((s) => s.addCategory); const addProject = useAppStore((s) => s.addProject)
  const [title, setTitle] = useState(task?.title ?? ''); const [description, setDescription] = useState(task?.description ?? ''); const [project, setProject] = useState(task?.project_id ?? ''); const [category, setCategory] = useState(task?.category_id ?? ''); const [importance, setImportance] = useState(task?.importance_score ?? 50); const [urgency, setUrgency] = useState(task?.urgency_score ?? 50); const [estimate, setEstimate] = useState(task && task.estimated_focus_minutes > 0 ? String(task.estimated_focus_minutes) : ''); const [due, setDue] = useState(task ? toLocalInput(task.due_date) : initialDate ? `${initialDate}T18:00` : ''); const [tags, setTags] = useState(task?.tags.join(', ') ?? ''); const [recurrence, setRecurrence] = useState<'none' | 'daily' | 'weekdays' | 'weekly' | 'monthly'>(task?.recurrence ?? 'none'); const [newCategory, setNewCategory] = useState(''); const [newProject, setNewProject] = useState('')
  const priority = useMemo<Priority>(() => importance >= 75 && urgency >= 75 ? 'urgent' : importance >= 60 ? 'high' : urgency >= 60 ? 'medium' : importance >= 35 || urgency >= 35 ? 'low' : 'none', [importance, urgency])
  function submit(event: React.FormEvent) { event.preventDefault(); if (!title.trim()) return; const values = { title: title.trim(), description: description.trim(), project_id: project || null, category_id: category || null, importance_score: importance, urgency_score: urgency, priority, estimated_focus_minutes: estimate === '' ? 0 : Math.max(0, Number(estimate)), due_date: fromLocalInput(due), scheduled_date: task?.scheduled_date ?? initialDate ?? null, tags: tags.split(/[,，\s]+/).map((x) => x.trim()).filter(Boolean), recurrence }; if (task) updateTask(task.id, values); else addTask(values); onDone() }
  return <form className="task-form" onSubmit={submit}>
    <Field label={t('tasks.titleLabel')}><Input autoFocus value={title} onChange={(e) => setTitle(e.target.value)} required /></Field>
    <Field label={t('tasks.description')}><Textarea rows={3} value={description} onChange={(e) => setDescription(e.target.value)} /></Field>
    <div className="form-grid"><Field label={t('tasks.project')}><Select value={project} onChange={(e) => setProject(e.target.value)}><option value="">{t('tasks.noProject')}</option>{projects.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</Select></Field><Field label={t('tasks.category')}><Select value={category} onChange={(e) => setCategory(e.target.value)}><option value="">{t('tasks.noCategory')}</option>{categories.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</Select></Field></div>
    <div className="inline-create"><Input placeholder={t('tasks.addProject')} value={newProject} onChange={(e) => setNewProject(e.target.value)} /><Button size="sm" onClick={() => { if (newProject.trim()) { const x = addProject(newProject.trim()); setProject(x.id); setNewProject('') } }}>+</Button><Input placeholder={t('tasks.addCategory')} value={newCategory} onChange={(e) => setNewCategory(e.target.value)} /><Button size="sm" onClick={() => { if (newCategory.trim()) { const x = addCategory(newCategory.trim()); setCategory(x.id); setNewCategory('') } }}>+</Button></div>
    <div className="form-grid"><Field label={`${t('tasks.importance')} · ${importance}`}><Input type="range" min="0" max="100" value={importance} onChange={(e) => setImportance(Number(e.target.value))} /></Field><Field label={`${t('tasks.urgency')} · ${urgency}`}><Input type="range" min="0" max="100" value={urgency} onChange={(e) => setUrgency(Number(e.target.value))} /></Field></div>
    <div className="form-grid"><Field label={t('tasks.estimate')} hint={t('tasks.estimateHint')}><Input type="number" min="1" max="14400" value={estimate} onChange={(e) => setEstimate(e.target.value)} placeholder={t('tasks.estimateOptional')} /></Field><Field label={t('tasks.due')}><Input type="datetime-local" value={due} onChange={(e) => setDue(e.target.value)} /></Field></div>
    <div className="form-grid"><Field label={t('tasks.tags')}><Input value={tags} onChange={(e) => setTags(e.target.value)} placeholder="python, deep-work" /></Field><Field label={t('tasks.recurrence')}><Select value={recurrence} onChange={(e) => setRecurrence(e.target.value as typeof recurrence)}><option value="none">{t('recurrence.none')}</option><option value="daily">{t('recurrence.daily')}</option><option value="weekdays">{t('recurrence.weekdays')}</option><option value="weekly">{t('recurrence.weekly')}</option><option value="monthly">{t('recurrence.monthly')}</option></Select></Field></div>
    <div className="form-footer"><Button variant="ghost" onClick={onDone}>{t('common.cancel')}</Button><Button variant="primary" type="submit">{t('common.save')}</Button></div>
  </form>
}
