import dayjs from 'dayjs'
import { ArrowRight, CheckCircle2, Clock3, Flame, ListTodo, Play, StickyNote } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { lazy, Suspense } from 'react'
import { TaskCollection } from '../features/tasks/TaskCollection'
import { useAppStore } from '../stores/app-store'
import { formatMinutes, localDate } from '../utils/time'

const FocusChart = lazy(() => import('../components/charts/FocusChart').then((module) => ({ default: module.FocusChart })))

export function DashboardPage() {
  const { t } = useTranslation(); const data = useAppStore((s) => s.data); const today = localDate(); const start = dayjs().startOf('week').add(1, 'day'); const days = Array.from({ length: 7 }, (_, i) => start.add(i, 'day')); const activeSessions = data.sessions.filter((x) => !x.deleted_at && x.completed); const todaySeconds = activeSessions.filter((x) => x.start_time.slice(0, 10) === today).reduce((sum, x) => sum + x.duration_seconds, 0); const weekValues = days.map((day) => Math.round(activeSessions.filter((x) => dayjs(x.start_time).isSame(day, 'day')).reduce((sum, x) => sum + x.duration_seconds, 0) / 60)); const todayTasks = data.tasks.filter((x) => !x.deleted_at && x.status !== 'archived' && (x.scheduled_date === today || x.due_date?.slice(0, 10) === today)).slice(0, 5); const completed = data.tasks.filter((x) => x.completed_at?.slice(0, 10) === today).length; const focusDays = new Set(activeSessions.filter((x) => x.duration_seconds >= data.settings.streakMinutes * 60).map((x) => x.start_time.slice(0, 10))); let streak = 0; let cursor = dayjs(); if (!focusDays.has(cursor.format('YYYY-MM-DD'))) cursor = cursor.subtract(1, 'day'); while (focusDays.has(cursor.format('YYYY-MM-DD'))) { streak++; cursor = cursor.subtract(1, 'day') }
  const metrics = [[t('dashboard.todayTasks'), todayTasks.filter((x) => x.status !== 'done').length, ListTodo], [t('dashboard.completed'), completed, CheckCircle2], [t('dashboard.focusToday'), formatMinutes(todaySeconds / 60), Clock3], [t('dashboard.streak'), `${streak} ${t('dashboard.days')}`, Flame]] as const
  const quote = data.settings.dashboardQuote.trim() || t('dashboard.greeting')
  return <div className="page dashboard"><div className="dashboard-hero"><div><span>{dayjs().format('YYYY · MM · DD')}</span><h1>{quote}</h1></div><Link to="/focus" className="primary-link"><Play size={16} />{t('dashboard.quickStart')}</Link></div><div className="metric-grid">{metrics.map(([label, value, Icon]) => <article className="metric-card" key={label}><div className="metric-icon"><Icon size={18} /></div><span>{label}</span><strong>{value}</strong></article>)}</div><div className="dashboard-grid"><section className="panel panel-wide"><header className="panel-header"><div><h2>{t('dashboard.todayTasks')}</h2><p>{todayTasks.length} {t('dashboard.items')}</p></div><Link to="/today">{t('common.all')}<ArrowRight size={14} /></Link></header>{todayTasks.length ? <TaskCollection tasks={todayTasks} projects={data.projects} categories={data.categories} view="compact" /> : <div className="mini-empty"><CheckCircle2 size={24} /><span>{t('tasks.empty')}</span></div>}</section><section className="panel"><header className="panel-header"><div><h2>{t('dashboard.trend')}</h2><p>{formatMinutes(weekValues.reduce((a, b) => a + b, 0))}</p></div></header><Suspense fallback={<div className="chart-loading" />}><FocusChart labels={days.map((x) => x.format('dd'))} values={weekValues} height={210} /></Suspense></section><section className="panel"><header className="panel-header"><div><h2>{t('dashboard.recentMemos')}</h2></div><Link to="/memo" aria-label={t('dashboard.recentMemos')}><ArrowRight size={14} /></Link></header><div className="memo-list">{data.memos.filter((x) => !x.deleted_at).slice(0, 4).map((memo) => <Link to="/memo" key={memo.id}><StickyNote size={15} /><div><strong>{memo.title || t('memo.untitled')}</strong><span>{memo.content.slice(0, 60)}</span></div></Link>)}</div></section></div></div>
}
