import { Database, Download, HardDriveDownload, MonitorUp, Palette, RotateCcw, TimerReset, Upload } from 'lucide-react'
import { useRef, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { PageHeader } from '../components/shared/PageHeader'
import { Button } from '../components/ui/Button'
import { Field, Input, Select, Switch } from '../components/ui/Field'
import { defaultSettings } from '../services/defaults'
import { useAppStore } from '../stores/app-store'
import type { AppSettings, PanelPreferences } from '../types/domain'

function SettingsSection({ title, icon: Icon, children }: { title: string; icon: typeof Palette; children: React.ReactNode }) { return <section className="settings-section"><header><div><Icon size={18} /></div><h2>{title}</h2></header><div className="settings-body">{children}</div></section> }
function NumberSetting({ label, value, min, max, suffix, onChange }: { label: string; value: number; min: number; max: number; suffix?: string; onChange(value: number): void }) { return <Field label={label}><div className="number-field"><Input type="number" value={value} min={min} max={max} onChange={(e) => onChange(Math.min(max, Math.max(min, Number(e.target.value))))} /><span>{suffix}</span></div></Field> }
function PanelSettings({ title, value, onChange }: { title: string; value: PanelPreferences; onChange(value: PanelPreferences): void }) { const { t } = useTranslation(); return <div className="sub-settings"><h3>{title}</h3><Switch label={t('settings.enabled')} checked={value.enabled} onChange={(enabled) => onChange({ ...value, enabled })} /><Switch label={t('settings.alwaysTop')} checked={value.zOrder === 'alwaysOnTop'} onChange={(checked) => onChange({ ...value, zOrder: checked ? 'alwaysOnTop' : 'normal' })} /><Switch label={t('settings.positionLock')} checked={value.positionLocked} onChange={(positionLocked) => onChange({ ...value, positionLocked })} /><Switch label={t('settings.snap')} checked={value.snapEnabled} onChange={(snapEnabled) => onChange({ ...value, snapEnabled })} /><Field label={`${t('settings.opacity')} · ${Math.round(value.backgroundOpacity * 100)}%`}><Input type="range" min="0" max="1" step="0.05" value={value.backgroundOpacity} onChange={(e) => onChange({ ...value, backgroundOpacity: Number(e.target.value) })} /></Field></div> }

export function SettingsPage() {
  const { t } = useTranslation(); const settings = useAppStore((s) => s.data.settings); const update = useAppStore((s) => s.updateSettings); const exportJson = useAppStore((s) => s.exportJson); const exportCsv = useAppStore((s) => s.exportCsv); const backup = useAppStore((s) => s.backup); const importJson = useAppStore((s) => s.importJson); const input = useRef<HTMLInputElement>(null); const [dataMessage, setDataMessage] = useState(''); const set = <K extends keyof AppSettings>(key: K, value: AppSettings[K]) => update({ [key]: value } as Pick<AppSettings, K>)
  return <div className="page settings-page"><PageHeader title={t('settings.title')} subtitle={t('settings.subtitle')} actions={<Button onClick={() => update(structuredClone(defaultSettings))}><RotateCcw size={15} />{t('common.reset')}</Button>} /><div className="settings-grid"><SettingsSection title={t('settings.appearance')} icon={Palette}><Field label={t('settings.theme')}><Select value={settings.theme} onChange={(e) => set('theme', e.target.value as AppSettings['theme'])}><option value="system">{t('settings.system')}</option><option value="light">{t('settings.light')}</option><option value="dark">{t('settings.dark')}</option></Select></Field><Field label={t('settings.language')}><Select value={settings.language} onChange={(e) => set('language', e.target.value as AppSettings['language'])}><option value="zh-CN">简体中文</option><option value="en-US">English</option></Select></Field><Field label={t('settings.accent')}><Input type="color" value={settings.accentColor} onChange={(e) => set('accentColor', e.target.value)} /></Field><Field label={t('settings.dashboardQuote')} hint={t('settings.dashboardQuoteHint')}><Input value={settings.dashboardQuote} maxLength={80} placeholder={t('dashboard.greeting')} onChange={(e) => set('dashboardQuote', e.target.value)} /></Field></SettingsSection>
    <SettingsSection title={t('settings.timer')} icon={TimerReset}><div className="form-grid"><NumberSetting label={t('settings.pomodoro')} value={settings.pomodoroMinutes} min={1} max={240} suffix={t('common.minutes')} onChange={(v) => set('pomodoroMinutes', v)} /><NumberSetting label={t('settings.streakGoal')} value={settings.streakMinutes} min={1} max={1440} suffix={t('common.minutes')} onChange={(v) => set('streakMinutes', v)} /><NumberSetting label={t('settings.minimumPercent')} value={settings.minimumRecordPercent} min={0} max={100} suffix="%" onChange={(v) => set('minimumRecordPercent', v)} /><NumberSetting label={t('settings.exemption')} value={settings.thresholdExemptionMinutes} min={1} max={14400} suffix={t('common.minutes')} onChange={(v) => set('thresholdExemptionMinutes', v)} /></div><Switch label={t('settings.preventSleep')} checked={settings.preventSleep} onChange={(v) => set('preventSleep', v)} /><Switch label={t('settings.autoOvertime')} checked={settings.autoOvertime} onChange={(v) => set('autoOvertime', v)} />{settings.autoOvertime && <NumberSetting label={t('settings.overtime')} value={settings.overtimeMinutes} min={1} max={240} suffix={t('common.minutes')} onChange={(v) => set('overtimeMinutes', v)} />}</SettingsSection>
    <SettingsSection title={t('settings.matrix')} icon={MonitorUp}><div className="form-grid"><NumberSetting label={t('settings.fourThreshold')} value={settings.matrixFourThreshold} min={1} max={99} onChange={(v) => set('matrixFourThreshold', v)} /><NumberSetting label={t('settings.nineLow')} value={settings.matrixNineLow} min={1} max={98} onChange={(v) => set('matrixNineLow', v)} /><NumberSetting label={t('settings.nineHigh')} value={settings.matrixNineHigh} min={2} max={99} onChange={(v) => set('matrixNineHigh', v)} /></div></SettingsSection>
    <SettingsSection title={t('settings.desktop')} icon={MonitorUp}><Switch label={t('settings.closeToTray')} checked={settings.closeToTray} onChange={(v) => set('closeToTray', v)} /><p className="settings-note">{t('settings.closeToTrayHint')}</p><PanelSettings title={t('settings.taskPanel')} value={settings.taskPanel} onChange={(v) => set('taskPanel', v)} /><PanelSettings title={t('settings.timerPanel')} value={settings.timerPanel} onChange={(v) => set('timerPanel', v)} /><p className="settings-note">{t('settings.noShortcut')}</p></SettingsSection>
    <SettingsSection title={t('settings.data')} icon={Database}><Switch label={t('settings.autoBackup')} checked={settings.autoBackup} onChange={(v) => set('autoBackup', v)} /><div className="data-actions"><Button onClick={exportJson}><Download size={16} />{t('common.export')} JSON</Button><Button onClick={exportCsv}><Download size={16} />{t('common.export')} CSV</Button><Button onClick={() => input.current?.click()}><Upload size={16} />{t('common.import')} JSON</Button><Button onClick={() => { void backup().then((path) => setDataMessage(path ? `${t('settings.backupSaved')}: ${path}` : t('settings.previewBackup'))) }}><HardDriveDownload size={16} />{t('settings.backupDatabase')}</Button><input ref={input} type="file" accept="application/json,.json" hidden onChange={(e) => { const file = e.target.files?.[0]; if (file) void importJson(file).then(() => setDataMessage(t('settings.imported'))) }} /></div>{dataMessage && <p className="settings-message">{dataMessage}</p>}<p className="settings-note">{t('settings.importNote')}</p></SettingsSection></div></div>
}
